version: '3.9'

services:
  elastic-service:
    container_name: elastic-service
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - elastic-service-logs:/app/logs
      - ./src/main/resources/kafka.server.keystore.jks:/app/kafka.server.keystore.jks
      - ./src/main/resources/kafka.server.truststore.jks:/app/kafka.server.truststore.jks

volumes:
  elastic-service-logs: